// Mock data for groups
export const mockGroups = [
    {
        id: "group-1",
        name: "Family Group",
        image: "https://picsum.photos/200?random=1",
        lastMessage: "When are we meeting for dinner?",
        lastMessageTime: "10:30 AM",
        members: ["Mom", "Dad", "Sis", "You"],
    },
    {
        id: "group-2",
        name: "Work Team",
        image: "https://picsum.photos/200?random=2",
        lastMessage: "Meeting postponed to 3 PM",
        lastMessageTime: "Yesterday",
        members: ["Alex", "Emma", "David", "You"],
    },
    {
        id: "group-3",
        name: "Gaming Squad",
        image: "https://picsum.photos/200?random=3",
        lastMessage: "Anyone up for a game tonight?",
        lastMessageTime: "2 days ago",
        members: ["Chris", "Jake", "Lisa", "You"],
    },
    {
        id: "group-4",
        name: "Book Club",
        image: "https://picsum.photos/200?random=4",
        lastMessage: "I finished the book, it was amazing!",
        lastMessageTime: "3 days ago",
        members: ["Rachel", "Monica", "Phoebe", "You"],
    },
];

// Mock data for messages
export const mockMessages = [
    {
        id: "msg-1",
        groupId: "group-1",
        senderId: "user-1",
        senderName: "John",
        content: "Hey everyone! When are we meeting for dinner?",
        timestamp: "2023-05-10T10:30:00Z",
    },
    {
        id: "msg-2",
        groupId: "group-1",
        senderId: "user-2",
        senderName: "Sarah",
        content: "I'm free after 7 PM",
        timestamp: "2023-05-10T10:35:00Z",
    },
    {
        id: "msg-3",
        groupId: "group-1",
        senderId: "current-user",
        senderName: "You",
        content: "Works for me too!",
        timestamp: "2023-05-10T10:40:00Z",
    },
    {
        id: "msg-4",
        groupId: "group-1",
        senderId: "user-3",
        senderName: "Mike",
        content: "Let's meet at the usual place at 7:30 PM then",
        timestamp: "2023-05-10T10:45:00Z",
    },
    {
        id: "msg-5",
        groupId: "group-2",
        senderId: "user-4",
        senderName: "Alex",
        content: "Team, the client meeting needs to be rescheduled",
        timestamp: "2023-05-09T14:20:00Z",
    },
    {
        id: "msg-6",
        groupId: "group-2",
        senderId: "user-5",
        senderName: "Emma",
        content: "What time works for everyone?",
        timestamp: "2023-05-09T14:25:00Z",
    },
    {
        id: "msg-7",
        groupId: "group-2",
        senderId: "user-6",
        senderName: "David",
        content: "I'm available after 3 PM",
        timestamp: "2023-05-09T14:30:00Z",
    },
    {
        id: "msg-8",
        groupId: "group-2",
        senderId: "current-user",
        senderName: "You",
        content: "3 PM works for me as well",
        timestamp: "2023-05-09T14:35:00Z",
    },
    {
        id: "msg-9",
        groupId: "group-2",
        senderId: "user-4",
        senderName: "Alex",
        content: "Meeting postponed to 3 PM",
        timestamp: "2023-05-09T14:40:00Z",
    },
];